### ISSUE TITLE
expo-av

### ISSUE THREAD

**Issue by huyawei** [zhiqingchen/taro-test#2]
git clone xxxx
yarn install
yarn upgradePeerdeps
yarn build:rn --platform android
cd android
gradlew assembleRelease

* Where:
Script 'E:\workspace\my\taro-test\node_modules\expo-modules-autolinking\scripts\android\autolinking_implementation.gradle' line: 272

* What went wrong:
A problem occurred evaluating project ':expo'.
> A problem occurred configuring project ':expo-av'

**Comment by zhiqingchen** [comment]
https://github.com/zhiqingchen/taro-test/actions

对比 GitHub action 的编译
